### ISSUE TITLE
Hosting Environment Blocking HTTP Requests - Error 403 Forbidden

### ISSUE THREAD

**Issue by huypv2002** [DavideViolante/socialblade-com-api#101]
I am encountering an issue with my hosting environment where HTTP requests to a specific URL are being blocked, resulting in a 403 Forbidden error. The same requests work perfectly on my local development environment.

Details:
URL: https://socialblade.com/youtube/channel/UCKc5D_o4etjuQwgUZ9eKCLQ
Error: 403 Forbidden

Despite these efforts, the hosting environment continues to return a 403 Forbidden status. I suspect that the IP address of the hosting server might be blocked or there might be firewall/security rules preventing the requests.

Could you please assist me in resolving this issue? Any insights or suggestions would be greatly appreciated.

Thank you for your support and understanding.

**Comment by DavideViolante** [comment]
If the IP of the hosting is blocked or similar, only scraperapi.com comes in my mind. They offer a free plan with 1k requests.

**Comment by huypv2002** [comment]
Thank you very much Davide, I found a way to avoid having my ip blocked. I configured the proxy, ip and user agent in the .htaccess file and it worked for me.
