### ISSUE TITLE
Add TikTok Data

### ISSUE THREAD

**Issue by sferez** [DavideViolante/socialblade-com-api#84]
Social Blade has a TikTok section in beta, which can be valuable to add.

<img width="1278" alt="image" src="https://github.com/DavideViolante/socialblade-com-api/assets/91850099/90662391-8d86-4ae4-8431-3ed0a337251c">

I believe the data of the graph is located in the same script publicly available (see below)

<img width="961" alt="image" src="https://github.com/DavideViolante/socialblade-com-api/assets/91850099/91aeeb18-5ffb-44af-9ceb-847a051d2de4">

**Comment by DavideViolante** [comment]
I added it in v3.2.0, but I didn't test it deeply, but it seems to work. Let me know if it's ok. Thank you
