### ISSUE TITLE
convertUnit Improvement

### ISSUE THREAD

**Issue by sferez** [DavideViolante/socialblade-com-api#85]
It seems like the function convertUnit could have a little improvement because it was reporting false values for some youtube accounts.

Here for example the value of selenagomez subscribers is not converted correctly.
_*Most recent data to 0, previous day not converted correctly_
```
{
      date: '2023/09/25',
      subscribersDelta: 0,
      subscribers: 34.1,
      viewsDelta: 0,
      views: 13309394169
    },
    {
      date: '2023/09/26',
      subscribersDelta: 0,
      subscribers: 0,
      viewsDelta: 0,
      views: 13309394169
    }
```

Here is a proposal for improvement:
```
function convertUnit(str) {
  str = str.replace(/LIVE/g, '');
  if (str.includes('K') || str.includes('M')) {
    str = str.replace(/\./g, '')
  }
  str = str.replace(/K/g, '000').replace(/M/g, '000000');
  return str;
}
```

One Line:
```
function convertUnit(str) {
  return str.replace(/LIVE/g, '').replace(/K/g, '000').replace(/M/g, '000000').replace(/\./g, '');
}
```

Step 1: remove the "LIVE" info that could be there for the most recent datapoint
Step 2: if there is a . remove it, otherwise, the replacement of K or M will result in nothing afterwards
Step 3: Replace the K and M by the correct number of 0

New result for selenagomez from the proposal code snippet
```
{
      date: '2023/09/25',
      subscribersDelta: 0,
      subscribers: 341000000,
      viewsDelta: 0,
      views: 13309394169
    },
    {
      date: '2023/09/26',
      subscribersDelta: 0,
      subscribers: 341000000,
      viewsDelta: 0,
      views: 13309394169
    }
```

**Comment by DavideViolante** [comment]
Thank you for reporting, your function was almost correct, but when there is a dot, you should remove one 0.
In your example this is not 34.1M -> 341.000.000 but 341M
Anyway I fixed in the related commit.
