### ISSUE TITLE
Youtube URL Fix

### ISSUE THREAD

**Issue by sferez** [DavideViolante/socialblade-com-api#86]
It seems that the URL generated for YouTube does not provide the 30D period for the table, but only the 14D-ish period.

The reason is that the URL is generated us as follows:
```
function generateUrl(source, username) {
  const userUrlCriteria = {
    facebook: 'page',
    youtube: 'channel',
  };
  const userUrl = userUrlCriteria[source] || 'user';
  const urlSuffix = source === 'facebook' ? '' : '/monthly';
  return `https://socialblade.com/${source}/${userUrl}/${username}${urlSuffix}`;
}
```
I think Social Blade updated their URL and now if you pass the 'channel' inside the URL it will redirect you to the user summary page and not the detailed statistics one.

The solution here is to pass the new URL with only 'c' as follows:
```
function generateUrl(source, username) {
  const userUrlCriteria = {
    facebook: 'page',
    youtube: 'c',
  };
  const userUrl = userUrlCriteria[source] || 'user';
  const urlSuffix = source === 'facebook' ? '' : '/monthly';
  return `https://socialblade.com/${source}/${userUrl}/${username}${urlSuffix}`;
}
```
This way the page access is: https:// socialblade .com/youtube/c/{username}/monthly

**Comment by sferez** [comment]
Update: it seems that some account 'channel' work and for some 'c' work

**Comment by sferez** [comment]
The fix that seems to work is to have by default the URL with 'c' for YouTube, as you usually work with the YouTube username and not the YouTube ID. In the case of a redirect to the 'channel' page (it means that Social Blade is using the youtube_id for its page) it will be redirected to the user summary and not the details statistics.

So when accessing the page we need to check if a redirect occurs and if we lost the /monthly property, if so we can add /monthly to the newly generated URL

```
await page.goto(url);
const currentUrl = await page.url();
if (!currentUrl.endsWith('monthly') && url.endsWith('monthly')) {
  console.log('Redirecting to monthly');
  await page.goto(currentUrl + '/monthly');
}
```

I didn't do exhaustive testing but it seems to work with all the artists I'm dealing with.

**Comment by DavideViolante** [comment]
Thank you @sferez for the detailed replies. Can you please tell me some youtube usernames and user ids so I do some tests?
Using 'c' with selenagomez returns correctly 30 days. I think I need some other usernames or user ids where it does not work the 'c'. Thanks

**Comment by sferez** [comment]
Some examples:

tamerhosny : use 'c'
imbryantbarnes : use 'channel'
ryanmackmusic : use 'c'
dylangossettmusic : use 'channel'
